import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import react from "@astrojs/react";
import node from "@astrojs/node";
import fs from "node:fs";
import remarkPythonRefs from "./src/plugins/remark-python-refs";

const isDev = process.env.NODE_ENV === "development" || process.argv.includes("dev");
const isStatic = process.env.BUILD_TARGET === "static";
const useServer = isDev || !isStatic;

// Load redirects generated by the migration script
// Astro prepends `base` to the redirect source but not the target,
// so we prepend it ourselves for non-root deployments.
const base = isStatic ? "/psf-blog" : "";
let redirects: Record<string, string> = {};
try {
  const redirectsPath = new URL("./src/data/redirects.json", import.meta.url);
  const raw: Record<string, string> = JSON.parse(fs.readFileSync(redirectsPath, "utf-8"));
  for (const [from, to] of Object.entries(raw)) {
    redirects[from] = `${base}${to}`;
  }
} catch {
  // No redirects file yet (run migration first)
}

// Blogger feed URLs → new RSS feed
redirects["/feeds/posts/default"] = `${base}/rss.xml`;

// Keystatic requires server rendering
const integrations = [mdx(), sitemap(), react()];
if (useServer) {
  const keystatic = (await import("@keystatic/astro")).default;
  integrations.push(keystatic());
}

// BUILD_TARGET=static  → GitHub Pages (static, /psf-blog base)
// default              → Cabotage / dev (server mode with Keystatic)
export default defineConfig({
  site: isStatic ? "https://jacobcoffee.github.io" : (process.env.SITE_URL || "http://localhost:4321"),
  base: isStatic ? "/psf-blog" : "/",
  integrations,
  output: useServer ? "server" : "static",
  ...(useServer && {
    adapter: node({ mode: "standalone" }),
  }),
  markdown: {
    remarkPlugins: [remarkPythonRefs],
  },
  redirects,
});
