import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import react from "@astrojs/react";
import node from "@astrojs/node";
import keystatic from "@keystatic/astro";
import fs from "node:fs";
import remarkPythonRefs from "./src/plugins/remark-python-refs";

// Load redirects generated by the migration script
let redirects: Record<string, string> = {};
try {
  const redirectsPath = new URL("./src/data/redirects.json", import.meta.url);
  const raw: Record<string, string> = JSON.parse(fs.readFileSync(redirectsPath, "utf-8"));
  for (const [from, to] of Object.entries(raw)) {
    redirects[from] = to;
  }
} catch {
  // No redirects file yet (run migration first)
}

// Blogger feed URLs → new RSS feed
redirects["/feeds/posts/default"] = "/rss.xml";

export default defineConfig({
  site: process.env.SITE_URL || "http://localhost:4321",
  integrations: [mdx(), sitemap(), react(), keystatic()],
  output: "server",
  adapter: node({ mode: "standalone" }),
  markdown: {
    remarkPlugins: [remarkPythonRefs],
  },
  redirects,
});
